In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully!")

All libraries imported successfully!

In [1]:
from pathlib import Path

DATA_DIR = Path("../data")

print("Data folder exists:", DATA_DIR.exists())

csv_files = sorted(DATA_DIR.glob("*.csv"))

print("Total CSV files:", len(csv_files))

for file in csv_files:
    print(file.name)

Data folder exists: False
Total CSV files: 0

In [2]:
import os

print(os.getcwd())

C:\Users\ishag\OneDrive\photos for ppt\Desktop\Ecommerce-Customer-Analytics

In [3]:
from pathlib import Path

DATA_DIR = Path(
    r"C:\Users\ishag\OneDrive\photos for ppt\Desktop\Ecommerce-Customer-Analytics\data"
)

print("Data folder exists:", DATA_DIR.exists())

if DATA_DIR.exists():
    for file in sorted(DATA_DIR.glob("*.csv")):
        print(file.name)

Data folder exists: True
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [8]:
# Load the Olist datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

orders = pd.read_csv(DATA_DIR / "olist_orders_dataset.csv")
customers = pd.read_csv(DATA_DIR / "olist_customers_dataset.csv")
items = pd.read_csv(DATA_DIR / "olist_order_items_dataset.csv")
products = pd.read_csv(DATA_DIR / "olist_products_dataset.csv")
payments = pd.read_csv(DATA_DIR / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(DATA_DIR / "olist_order_reviews_dataset.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [9]:
print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Order Items:", items.shape)
print("Products:", products.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)

Orders: (99441, 8)
Customers: (99441, 5)
Order Items: (112650, 7)
Products: (32951, 9)
Payments: (103886, 5)
Reviews: (99224, 7)

In [10]:
display(orders.head())
display(customers.head())
display(items.head())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [11]:
orders = pd.read_csv(DATA_DIR / "olist_orders_dataset.csv")

print("Dataset loaded successfully!")
print("Rows and columns:", orders.shape)

Dataset loaded successfully!
Rows and columns: (99441, 8)

In [12]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [13]:
datasets = {
    "orders": orders,
    "customers": customers,
    "items": items,
    "products": products,
    "payments": payments,
    "reviews": reviews
}
overview = []

for name, data in datasets.items():
    overview.append({
        "Dataset": name,
        "Rows": data.shape[0],
        "Columns": data.shape[1],
        "Duplicate_Rows": data.duplicated().sum(),
        "Total_Missing_Cells": data.isnull().sum().sum()
    })

overview_df = pd.DataFrame(overview)

display(overview_df)

     Dataset    Rows  Columns  Duplicate_Rows  Total_Missing_Cells
0     orders   99441        8               0                 4908
1  customers   99441        5               0                    0
2      items  112650        7               0                    0
3   products   32951        9               0                 2448
4   payments  103886        5               0                    0
5    reviews   99224        7               0               145903

In [14]:
for name, data in datasets.items():
    print(f"\n{'=' * 50}")
    print(f"DATASET: {name.upper()}")
    print("=" * 50)

    data.info()

==================================================
DATASET: ORDERS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

==================================================
DATASET: CUSTOMERS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

==================================================
DATASET: ITEMS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

==================================================
DATASET: PRODUCTS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

==================================================
DATASET: PAYMENTS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

==================================================
DATASET: REVIEWS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [15]:
missing_reports = []

for name, data in datasets.items():
    missing_count = data.isnull().sum()
    missing_pct = (data.isnull().mean() * 100).round(2)

    for column in data.columns:
        missing_reports.append({
            "Dataset": name,
            "Column": column,
            "Missing_Count": missing_count[column],
            "Missing_Percentage": missing_pct[column]
        })

missing_df = pd.DataFrame(missing_reports)

display(
    missing_df[missing_df["Missing_Count"] > 0]
    .sort_values(
        ["Dataset", "Missing_Percentage"],
        ascending=[True, False]
    )
)

     Dataset                         Column  Missing_Count  Missing_Percentage
6     orders  order_delivered_customer_date           2965                2.98
5     orders   order_delivered_carrier_date           1783                1.79
4     orders              order_approved_at            160                0.16
21  products          product_category_name            610                1.85
22  products            product_name_lenght            610                1.85
23  products     product_description_lenght            610                1.85
24  products             product_photos_qty            610                1.85
25  products               product_weight_g              2                0.01
26  products              product_length_cm              2                0.01
27  products              product_height_cm              2                0.01
28  products               product_width_cm              2                0.01
37   reviews           review_comment_title          87656               88.34
38   reviews         review_comment_message          58247               58.70

In [17]:
for name, data in datasets.items():
    print(
        f"{name}: "
        f"{data.duplicated().sum()} exact duplicate rows"
    )
key_checks = {
    "orders": ["order_id"],
    "customers": ["customer_id", "customer_unique_id"],
    "items": ["order_id", "order_item_id"],
    "products": ["product_id"],
    "payments": ["order_id", "payment_sequential"],
    "reviews": ["review_id", "order_id"]
}

for name, columns in key_checks.items():
    data = datasets[name]

    print(f"\n{name.upper()}")

    for column in columns:
        print(
            column,
            "unique values:",
            data[column].nunique(dropna=True),
            "out of",
            len(data),
            "rows"
        )

orders: 0 exact duplicate rows
customers: 0 exact duplicate rows
items: 0 exact duplicate rows
products: 0 exact duplicate rows
payments: 0 exact duplicate rows
reviews: 0 exact duplicate rows

ORDERS
order_id unique values: 99441 out of 99441 rows

CUSTOMERS
customer_id unique values: 99441 out of 99441 rows
customer_unique_id unique values: 96096 out of 99441 rows

ITEMS
order_id unique values: 98666 out of 112650 rows
order_item_id unique values: 21 out of 112650 rows

PRODUCTS
product_id unique values: 32951 out of 32951 rows

PAYMENTS
order_id unique values: 99440 out of 103886 rows
payment_sequential unique values: 29 out of 103886 rows

REVIEWS
review_id unique values: 98410 out of 99224 rows
order_id unique values: 98673 out of 99224 rows

In [18]:
print("ORDER ITEMS")
display(items[["price", "freight_value"]].describe())

print("PAYMENTS")
display(
    payments[["payment_value", "payment_installments"]].describe()
)

print("REVIEWS")
display(reviews[["review_score"]].describe())

ORDER ITEMS

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

PAYMENTS

       payment_value  payment_installments
count  103886.000000         103886.000000
mean      154.100380              2.853349
std       217.494064              2.687051
min         0.000000              0.000000
25%        56.790000              1.000000
50%       100.000000              1.000000
75%       171.837500              4.000000
max     13664.080000             24.000000

REVIEWS

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [19]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

print("Purchase date range:")
print(orders["order_purchase_timestamp"].min())
print(orders["order_purchase_timestamp"].max())

print("\nOrder statuses:")
display(orders["order_status"].value_counts(dropna=False))

Purchase date range:
2016-09-04 21:15:19
2018-10-17 17:30:18

Order statuses:

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [20]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

print("Purchase date range:")
print(orders["order_purchase_timestamp"].min())
print(orders["order_purchase_timestamp"].max())

print("\nOrder statuses:")
display(orders["order_status"].value_counts(dropna=False))

Purchase date range:
2016-09-04 21:15:19
2018-10-17 17:30:18

Order statuses:

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [21]:
for name, data in datasets.items():
    print("\n" + "=" * 50)
    print("DATASET:", name.upper())
    print("=" * 50)

    data.info()

==================================================
DATASET: ORDERS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

==================================================
DATASET: CUSTOMERS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

==================================================
DATASET: ITEMS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

==================================================
DATASET: PRODUCTS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

==================================================
DATASET: PAYMENTS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

==================================================
DATASET: REVIEWS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [22]:
missing_reports = []

for name, data in datasets.items():
    missing_count = data.isnull().sum()
    missing_pct = (data.isnull().mean() * 100).round(2)

    for column in data.columns:
        missing_reports.append({
            "Dataset": name,
            "Column": column,
            "Missing_Count": missing_count[column],
            "Missing_Percentage": missing_pct[column]
        })

missing_df = pd.DataFrame(missing_reports)

missing_df = missing_df[
    missing_df["Missing_Count"] > 0
].sort_values(
    ["Dataset", "Missing_Percentage"],
    ascending=[True, False]
)

display(missing_df)

     Dataset                         Column  Missing_Count  Missing_Percentage
6     orders  order_delivered_customer_date           2965                2.98
5     orders   order_delivered_carrier_date           1783                1.79
4     orders              order_approved_at            160                0.16
21  products          product_category_name            610                1.85
22  products            product_name_lenght            610                1.85
23  products     product_description_lenght            610                1.85
24  products             product_photos_qty            610                1.85
25  products               product_weight_g              2                0.01
26  products              product_length_cm              2                0.01
27  products              product_height_cm              2                0.01
28  products               product_width_cm              2                0.01
37   reviews           review_comment_title          87656               88.34
38   reviews         review_comment_message          58247               58.70

In [23]:
missing_reports = []

for name, data in datasets.items():
    missing_count = data.isnull().sum()
    missing_pct = (data.isnull().mean() * 100).round(2)

    for column in data.columns:
        missing_reports.append({
            "Dataset": name,
            "Column": column,
            "Missing_Count": missing_count[column],
            "Missing_Percentage": missing_pct[column]
        })

missing_df = pd.DataFrame(missing_reports)

missing_df = missing_df[
    missing_df["Missing_Count"] > 0
].sort_values(
    ["Dataset", "Missing_Percentage"],
    ascending=[True, False]
)

display(missing_df)

     Dataset                         Column  Missing_Count  Missing_Percentage
6     orders  order_delivered_customer_date           2965                2.98
5     orders   order_delivered_carrier_date           1783                1.79
4     orders              order_approved_at            160                0.16
21  products          product_category_name            610                1.85
22  products            product_name_lenght            610                1.85
23  products     product_description_lenght            610                1.85
24  products             product_photos_qty            610                1.85
25  products               product_weight_g              2                0.01
26  products              product_length_cm              2                0.01
27  products              product_height_cm              2                0.01
28  products               product_width_cm              2                0.01
37   reviews           review_comment_title          87656               88.34
38   reviews         review_comment_message          58247               58.70

In [24]:
for name, data in datasets.items():
    print(name, ":", data.duplicated().sum(), "duplicate rows")

orders : 0 duplicate rows
customers : 0 duplicate rows
items : 0 duplicate rows
products : 0 duplicate rows
payments : 0 duplicate rows
reviews : 0 duplicate rows

In [25]:
for name, data in datasets.items():
    print(name, ":", data.isnull().sum().sum(), "missing cells")

orders : 4908 missing cells
customers : 0 missing cells
items : 0 missing cells
products : 2448 missing cells
payments : 0 missing cells
reviews : 145903 missing cells

In [30]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

In [31]:
print(orders["order_status"].value_counts())

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [32]:
delivered_orders = orders[
    orders["order_status"] == "delivered"
].copy()

print("Total orders:", len(orders))
print("Delivered orders:", len(delivered_orders))

Total orders: 99441
Delivered orders: 96478

In [33]:
sales = delivered_orders.merge(
    items,
    on="order_id",
    how="inner"
)

sales["revenue"] = sales["price"] * 1

print("Sales rows:", sales.shape)
sales.head()

Sales rows: (110197, 15)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,revenue
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,29.99
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,118.70
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,159.90
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,45.00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,19.90

In [34]:
sales = sales.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

print("Missing customer IDs:", sales["customer_unique_id"].isna().sum())
sales.head()

Missing customer IDs: 0

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,revenue,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,29.99,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,118.70,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,159.90,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,45.00,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,19.90,72632f0f9dd73dfee390c9b22eb56dd6

In [35]:
total_revenue = sales["price"].sum()
total_orders = sales["order_id"].nunique()
total_customers = sales["customer_unique_id"].nunique()
average_order_value = total_revenue / total_orders

print("Item Revenue:", round(total_revenue, 2))
print("Delivered Orders:", total_orders)
print("Customers:", total_customers)
print("Average Order Value:", round(average_order_value, 2))

Item Revenue: 13221498.11
Delivered Orders: 96478
Customers: 93358
Average Order Value: 137.04

In [36]:
orders_per_customer = (
    sales.groupby("customer_unique_id")["order_id"]
    .nunique()
)

repeat_customers = orders_per_customer[
    orders_per_customer >= 2
]

repeat_rate = (
    len(repeat_customers) / len(orders_per_customer) * 100
)

print("Repeat customers:", len(repeat_customers))
print("Repeat customer rate (%):", round(repeat_rate, 2))

Repeat customers: 2801
Repeat customer rate (%): 3.0

In [37]:
# Remove records without a usable customer identity
sales_rfm = sales.dropna(
    subset=["customer_unique_id"]
).copy()

reference_date = (
    sales_rfm["order_purchase_timestamp"].max()
    + pd.Timedelta(days=1)
)

rfm = sales_rfm.groupby("customer_unique_id").agg(
    Last_Purchase=("order_purchase_timestamp", "max"),
    Frequency=("order_id", "nunique"),
    Monetary=("price", "sum")
)

rfm["Recency"] = (
    reference_date - rfm["Last_Purchase"]
).dt.days

rfm = rfm[
    ["Recency", "Frequency", "Monetary"]
]

rfm.head()

                                  Recency  Frequency  Monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      112          1    129.90
0000b849f77a49e4a4ce2b2a4ca5be3f      115          1     18.90
0000f46a3911fa3c0805444483337064      537          1     69.00
0000f6ccb0745a6a4b88665a16c9f078      321          1     25.99
0004aac84e0df4da2b147fca70cf8255      288          1    180.00

In [38]:
print("Total records in sales:", len(sales))
print("Customers with usable identity:", sales["customer_unique_id"].nunique())
print("Total customers in RFM:", len(rfm))

display(rfm.head(10))

Total records in sales: 110197
Customers with usable identity: 93358
Total customers in RFM: 93358

                                  Recency  Frequency  Monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      112          1    129.90
0000b849f77a49e4a4ce2b2a4ca5be3f      115          1     18.90
0000f46a3911fa3c0805444483337064      537          1     69.00
0000f6ccb0745a6a4b88665a16c9f078      321          1     25.99
0004aac84e0df4da2b147fca70cf8255      288          1    180.00
0004bd2a26a76fe21f786e4fbd80607f      146          1    154.00
00050ab1314c0e55a6ca13cf7181fecf      132          1     27.99
00053a61a98854899e70ed204dd4bafe      183          1    382.00
0005e1862207bf6ccc02e4228effd9a0      543          1    135.00
0005ef4cd20d2893f0d9fbd94d3c0d97      170          1    104.90

In [39]:
# Remove records without a usable customer identity
sales_rfm = sales.dropna(
    subset=["customer_unique_id"]
).copy()

# Reference date
reference_date = (
    sales_rfm["order_purchase_timestamp"].max()
    + pd.Timedelta(days=1)
)

# Calculate RFM for ALL customers
rfm = sales_rfm.groupby("customer_unique_id").agg(
    Last_Purchase=("order_purchase_timestamp", "max"),
    Frequency=("order_id", "nunique"),
    Monetary=("price", "sum")
)

# Calculate Recency
rfm["Recency"] = (
    reference_date - rfm["Last_Purchase"]
).dt.days

# Keep required columns
rfm = rfm[["Recency", "Frequency", "Monetary"]]

# Display ALL customers
print("Total customers:", len(rfm))
display(rfm)

Total customers: 93358

                                  Recency  Frequency  Monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      112          1    129.90
0000b849f77a49e4a4ce2b2a4ca5be3f      115          1     18.90
0000f46a3911fa3c0805444483337064      537          1     69.00
0000f6ccb0745a6a4b88665a16c9f078      321          1     25.99
0004aac84e0df4da2b147fca70cf8255      288          1    180.00
...                                   ...        ...       ...
fffcf5a5ff07b0908bd4e2dbc735a684      447          1   1570.00
fffea47cd6d3cc0a88bd621562a9d061      262          1     64.89
ffff371b4d645b6ecea244b27531430a      568          1     89.90
ffff5962728ec6157033ef9805bacc48      119          1    115.00
ffffd2657e2aad2907e67c3e9daecbeb      484          1     56.99

[93358 rows x 3 columns]

In [40]:
rfm.to_csv("customer_rfm_all.csv", index=True)

In [41]:
# Assign scores from 1 to 5
# Recency: lower days = better score
rfm["R_Score"] = pd.qcut(
    rfm["Recency"].rank(method="first"),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

# Frequency: higher orders = better score
rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

# Monetary: higher spending = better score
rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

# Combined RFM score
rfm["RFM_Score"] = (
    rfm["R_Score"].astype(str)
    + rfm["F_Score"].astype(str)
    + rfm["M_Score"].astype(str)
)

display(rfm)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score
customer_unique_id,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,129.90,4,1,4,414
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,18.90,4,1,1,411
0000f46a3911fa3c0805444483337064,537,1,69.00,1,1,2,112
0000f6ccb0745a6a4b88665a16c9f078,321,1,25.99,2,1,1,211
0004aac84e0df4da2b147fca70cf8255,288,1,180.00,2,1,5,215
...,...,...,...,...,...,...,...
fffcf5a5ff07b0908bd4e2dbc735a684,447,1,1570.00,1,5,5,155
fffea47cd6d3cc0a88bd621562a9d061,262,1,64.89,3,5,2,352
ffff371b4d645b6ecea244b27531430a,568,1,89.90,1,5,3,153
ffff5962728ec6157033ef9805bacc48,119,1,115.00,4,5,4,454
ffffd2657e2aad2907e67c3e9daecbeb,484,1,56.99,1,5,2,152

In [42]:
def segment_customer(row):
    if row["R_Score"] >= 4 and row["F_Score"] >= 4:
        return "Loyal / Best Customers"
    elif row["R_Score"] >= 4 and row["F_Score"] <= 2:
        return "Recent Customers"
    elif row["R_Score"] <= 2 and row["F_Score"] >= 3:
        return "At Risk Customers"
    elif row["R_Score"] <= 2 and row["F_Score"] <= 2:
        return "Lost / Inactive Customers"
    else:
        return "Regular Customers"

rfm["Customer_Segment"] = rfm.apply(
    segment_customer, axis=1
)

display(rfm)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Customer_Segment
customer_unique_id,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,129.90,4,1,4,414,Recent Customers
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,18.90,4,1,1,411,Recent Customers
0000f46a3911fa3c0805444483337064,537,1,69.00,1,1,2,112,Lost / Inactive Customers
0000f6ccb0745a6a4b88665a16c9f078,321,1,25.99,2,1,1,211,Lost / Inactive Customers
0004aac84e0df4da2b147fca70cf8255,288,1,180.00,2,1,5,215,Lost / Inactive Customers
...,...,...,...,...,...,...,...,...
fffcf5a5ff07b0908bd4e2dbc735a684,447,1,1570.00,1,5,5,155,At Risk Customers
fffea47cd6d3cc0a88bd621562a9d061,262,1,64.89,3,5,2,352,Regular Customers
ffff371b4d645b6ecea244b27531430a,568,1,89.90,1,5,3,153,At Risk Customers
ffff5962728ec6157033ef9805bacc48,119,1,115.00,4,5,4,454,Loyal / Best Customers
ffffd2657e2aad2907e67c3e9daecbeb,484,1,56.99,1,5,2,152,At Risk Customers

In [43]:
segment_summary = (
    rfm.groupby("Customer_Segment")
    .agg(
        Total_Customers=("Customer_Segment", "size"),
        Avg_Recency=("Recency", "mean"),
        Avg_Frequency=("Frequency", "mean"),
        Avg_Monetary=("Monetary", "mean")
    )
    .round(2)
    .sort_values("Total_Customers", ascending=False)
)

display(segment_summary)

,Total_Customers,Avg_Recency,Avg_Frequency,Avg_Monetary
Customer_Segment,,,,
Regular Customers,26160,182.86,1.02,136.50
At Risk Customers,22357,393.94,1.05,143.57
Lost / Inactive Customers,14986,395.51,1.00,140.88
Recent Customers,14984,90.88,1.00,139.31
Loyal / Best Customers,14871,89.71,1.09,150.77

In [44]:
# Convert order purchase timestamp to datetime
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"],
    errors="coerce"
)

# Keep delivered orders for consistent retention analysis
delivered_orders = orders[
    orders["order_status"] == "delivered"
].copy()

# Merge customer identity with orders
customer_orders = delivered_orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

# Remove records without customer identity
customer_orders = customer_orders.dropna(
    subset=["customer_unique_id", "order_purchase_timestamp"]
)

print("Delivered orders:", len(customer_orders))
print(
    "Unique customers:",
    customer_orders["customer_unique_id"].nunique()
)

display(customer_orders.head())

Delivered orders: 96478
Unique customers: 93358

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6

In [45]:
# All delivered orders with customer identity
customer_orders = delivered_orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

customer_orders = customer_orders.dropna(
    subset=["customer_unique_id", "order_purchase_timestamp"]
).copy()

customer_orders["order_purchase_timestamp"] = pd.to_datetime(
    customer_orders["order_purchase_timestamp"],
    errors="coerce"
)

customer_orders = customer_orders.dropna(
    subset=["order_purchase_timestamp"]
)

# Purchase month
customer_orders["Order_Month"] = (
    customer_orders["order_purchase_timestamp"].dt.to_period("M")
)

# First purchase month for every customer
customer_orders["Cohort_Month"] = (
    customer_orders.groupby("customer_unique_id")["Order_Month"]
    .transform("min")
)

# Months since first purchase
customer_orders["Cohort_Index"] = (
    (customer_orders["Order_Month"].dt.year -
     customer_orders["Cohort_Month"].dt.year) * 12
    + customer_orders["Order_Month"].dt.month
    - customer_orders["Cohort_Month"].dt.month
    + 1
)

print("Total eligible customers:",
      customer_orders["customer_unique_id"].nunique())

Total eligible customers: 93358

In [47]:
cohort_data = (
    customer_orders.groupby(
        ["Cohort_Month", "Cohort_Index"]
    )["customer_unique_id"]
    .nunique()
    .reset_index(name="Customers")
)

cohort_counts = cohort_data.pivot(
    index="Cohort_Month",
    columns="Cohort_Index",
    values="Customers"
)

# All cohort months and all available customer counts
cohort_sizes = cohort_counts[1]

retention = cohort_counts.div(cohort_sizes, axis=0) * 100

print("Total cohort months:", len(retention))
print("Retention table shape:", retention.shape)

display(retention.round(2))  # Full table, not just 5 rows

Total cohort months: 23
Retention table shape: (23, 20)

Cohort_Index,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21
Cohort_Month,,,,,,,,,,,,,,,,,,,,
2016-09,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,100.0,NaN,NaN,NaN,NaN,NaN,0.38,NaN,NaN,0.38,NaN,0.38,NaN,0.38,NaN,0.38,NaN,0.38,0.76,0.76
2016-12,100.0,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,100.0,0.28,0.28,0.14,0.42,0.14,0.42,0.14,0.14,NaN,0.42,0.14,0.70,0.42,0.14,0.14,0.28,0.42,0.14,NaN
2017-02,100.0,0.18,0.31,0.12,0.43,0.12,0.25,0.18,0.12,0.18,0.12,0.31,0.12,0.18,0.12,0.06,0.06,0.18,NaN,NaN
2017-03,100.0,0.44,0.36,0.40,0.36,0.16,0.16,0.32,0.32,0.08,0.36,0.12,0.20,0.12,0.16,0.24,0.08,0.12,NaN,NaN
2017-04,100.0,0.62,0.22,0.18,0.27,0.27,0.35,0.31,0.31,0.18,0.27,0.09,0.04,0.04,0.09,0.09,0.13,NaN,NaN,NaN
2017-05,100.0,0.46,0.46,0.29,0.29,0.32,0.41,0.14,0.26,0.26,0.26,0.35,0.23,0.03,0.17,0.20,NaN,NaN,NaN,NaN
2017-06,100.0,0.49,0.40,0.43,0.30,0.40,0.36,0.23,0.13,0.20,0.30,0.36,0.16,0.16,0.23,NaN,NaN,NaN,NaN,NaN
2017-07,100.0,0.53,0.35,0.24,0.29,0.21,0.32,0.11,0.19,0.27,0.21,0.29,0.13,0.24,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,100.0,0.69,0.35,0.27,0.35,0.52,0.30,0.27,0.15,0.15,0.25,0.20,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,100.0,0.70,0.55,0.27,0.45,0.22,0.22,0.25,0.27,0.17,0.25,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,100.0,0.72,0.25,0.09,0.23,0.21,0.21,0.37,0.28,0.18,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,100.0,0.57,0.37,0.17,0.17,0.18,0.11,0.18,0.13,0.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,100.0,0.21,0.28,0.34,0.26,0.21,0.17,0.02,0.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,100.0,0.34,0.37,0.29,0.29,0.16,0.18,0.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,100.0,0.35,0.40,0.30,0.25,0.22,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,100.0,0.40,0.30,0.30,0.12,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,100.0,0.59,0.30,0.24,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,100.0,0.52,0.26,0.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,100.0,0.43,0.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,100.0,0.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
# Count unique customers for each cohort month
# and month since first purchase

cohort_data = (
    customer_orders.groupby(
        ["Cohort_Month", "Cohort_Index"]
    )["customer_unique_id"]
    .nunique()
    .reset_index(name="Customers")
)

# Create cohort table
cohort_counts = cohort_data.pivot(
    index="Cohort_Month",
    columns="Cohort_Index",
    values="Customers"
)

# Calculate retention percentage
cohort_sizes = cohort_counts[1]

retention = cohort_counts.div(
    cohort_sizes, axis=0
) * 100

print("Total cohort months:", len(retention))
print("Cohort table dimensions:", retention.shape)

display(retention.round(2))

Total cohort months: 23
Cohort table dimensions: (23, 20)

Cohort_Index,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21
Cohort_Month,,,,,,,,,,,,,,,,,,,,
2016-09,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,100.0,NaN,NaN,NaN,NaN,NaN,0.38,NaN,NaN,0.38,NaN,0.38,NaN,0.38,NaN,0.38,NaN,0.38,0.76,0.76
2016-12,100.0,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,100.0,0.28,0.28,0.14,0.42,0.14,0.42,0.14,0.14,NaN,0.42,0.14,0.70,0.42,0.14,0.14,0.28,0.42,0.14,NaN
2017-02,100.0,0.18,0.31,0.12,0.43,0.12,0.25,0.18,0.12,0.18,0.12,0.31,0.12,0.18,0.12,0.06,0.06,0.18,NaN,NaN
2017-03,100.0,0.44,0.36,0.40,0.36,0.16,0.16,0.32,0.32,0.08,0.36,0.12,0.20,0.12,0.16,0.24,0.08,0.12,NaN,NaN
2017-04,100.0,0.62,0.22,0.18,0.27,0.27,0.35,0.31,0.31,0.18,0.27,0.09,0.04,0.04,0.09,0.09,0.13,NaN,NaN,NaN
2017-05,100.0,0.46,0.46,0.29,0.29,0.32,0.41,0.14,0.26,0.26,0.26,0.35,0.23,0.03,0.17,0.20,NaN,NaN,NaN,NaN
2017-06,100.0,0.49,0.40,0.43,0.30,0.40,0.36,0.23,0.13,0.20,0.30,0.36,0.16,0.16,0.23,NaN,NaN,NaN,NaN,NaN
2017-07,100.0,0.53,0.35,0.24,0.29,0.21,0.32,0.11,0.19,0.27,0.21,0.29,0.13,0.24,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,100.0,0.69,0.35,0.27,0.35,0.52,0.30,0.27,0.15,0.15,0.25,0.20,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,100.0,0.70,0.55,0.27,0.45,0.22,0.22,0.25,0.27,0.17,0.25,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,100.0,0.72,0.25,0.09,0.23,0.21,0.21,0.37,0.28,0.18,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,100.0,0.57,0.37,0.17,0.17,0.18,0.11,0.18,0.13,0.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,100.0,0.21,0.28,0.34,0.26,0.21,0.17,0.02,0.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,100.0,0.34,0.37,0.29,0.29,0.16,0.18,0.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,100.0,0.35,0.40,0.30,0.25,0.22,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,100.0,0.40,0.30,0.30,0.12,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,100.0,0.59,0.30,0.24,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,100.0,0.52,0.26,0.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,100.0,0.43,0.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,100.0,0.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
category_translation = pd.read_csv(
    DATA_DIR / "product_category_name_translation.csv"
)

display(category_translation.head())
print("Total rows:", len(category_translation))

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Total rows: 71

In [52]:
# Merge order items with product details
product_analysis = items.merge(
    products,
    on="product_id",
    how="left"
)

# Add English product category names
product_analysis = product_analysis.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

# Use English category where available
product_analysis["category"] = (
    product_analysis["product_category_name_english"]
    .fillna(product_analysis["product_category_name"])
    .fillna("Unknown")
)

# Calculate category-level sales and orders
category_summary = (
    product_analysis.groupby("category")
    .agg(
        Total_Items=("order_item_id", "count"),
        Unique_Orders=("order_id", "nunique"),
        Total_Sales=("price", "sum"),
        Total_Freight=("freight_value", "sum")
    )
    .sort_values("Total_Sales", ascending=False)
    .round(2)
)

# Display all categories
print("Total categories:", len(category_summary))
display(category_summary)

Total categories: 74

,Total_Items,Unique_Orders,Total_Sales,Total_Freight
category,,,,
health_beauty,9670,8836,1258681.34,182566.73
watches_gifts,5991,5624,1205005.68,100535.93
bed_bath_table,11115,9417,1036988.68,204693.04
sports_leisure,8641,7720,988048.97,168607.51
computers_accessories,7827,6689,911954.32,147318.08
...,...,...,...,...
flowers,33,29,1110.04,488.87
home_comfort_2,30,24,760.27,410.31
cds_dvds_musicals,14,12,730.00,224.99
fashion_childrens_clothes,8,8,569.85,95.51
security_and_services,2,2,283.29,41.22

In [54]:
# Keep delivered orders for customer purchase analysis
delivered_orders = orders[
    orders["order_status"] == "delivered"
].copy()

# Attach unique customer identity to each order
customer_analysis = delivered_orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

# Remove records without customer identity
# Include all orders, not only delivered orders
customer_analysis = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

# Remove records without usable customer identity
customer_analysis = customer_analysis.dropna(
    subset=["customer_unique_id"]
).copy()

customer_analysis["order_purchase_timestamp"] = pd.to_datetime(
    customer_analysis["order_purchase_timestamp"],
    errors="coerce"
)

# Summarize all available orders for each unique customer
customer_summary = (
    customer_analysis.groupby("customer_unique_id")
    .agg(
        Total_Orders=("order_id", "nunique"),
        First_Order=("order_purchase_timestamp", "min"),
        Last_Order=("order_purchase_timestamp", "max"),
        Order_Statuses=("order_status", "nunique")
    )
    .reset_index()
)

customer_summary["Customer_Type"] = np.where(
    customer_summary["Total_Orders"] > 1,
    "Repeat Customer",
    "One-Time Customer"
)

print("Total unique customers:", len(customer_summary))
display(customer_summary)  # Display all customers

Total unique customers: 96096

,customer_unique_id,Total_Orders,First_Order,Last_Order,Order_Statuses,Customer_Type
0,0000366f3b9a7992bf8c76cfdf3221e2,1,2018-05-10 10:56:27,2018-05-10 10:56:27,1,One-Time Customer
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,2018-05-07 11:11:27,2018-05-07 11:11:27,1,One-Time Customer
2,0000f46a3911fa3c0805444483337064,1,2017-03-10 21:05:03,2017-03-10 21:05:03,1,One-Time Customer
3,0000f6ccb0745a6a4b88665a16c9f078,1,2017-10-12 20:29:41,2017-10-12 20:29:41,1,One-Time Customer
4,0004aac84e0df4da2b147fca70cf8255,1,2017-11-14 19:45:42,2017-11-14 19:45:42,1,One-Time Customer
...,...,...,...,...,...,...
96091,fffcf5a5ff07b0908bd4e2dbc735a684,1,2017-06-08 21:00:36,2017-06-08 21:00:36,1,One-Time Customer
96092,fffea47cd6d3cc0a88bd621562a9d061,1,2017-12-10 20:07:56,2017-12-10 20:07:56,1,One-Time Customer
96093,ffff371b4d645b6ecea244b27531430a,1,2017-02-07 15:49:16,2017-02-07 15:49:16,1,One-Time Customer
96094,ffff5962728ec6157033ef9805bacc48,1,2018-05-02 15:17:41,2018-05-02 15:17:41,1,One-Time Customer
96095,ffffd2657e2aad2907e67c3e9daecbeb,1,2017-05-02 20:18:45,2017-05-02 20:18:45,1,One-Time Customer

In [57]:
from pathlib import Path

OUTPUT_DIR = Path(
    r"C:\Users\ishag\OneDrive\photos for ppt\Desktop\Ecommerce-Customer-Analytics\outputs"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Output folder ready:", OUTPUT_DIR.exists())

Output folder ready: True

In [58]:
customer_summary.to_csv(
    OUTPUT_DIR / "customer_purchase_analysis.csv",
    index=False
)

print("All customer records saved successfully.")
print("Total customers:", len(customer_summary))
print(
    "File saved:",
    (OUTPUT_DIR / "customer_purchase_analysis.csv").exists()
)

All customer records saved successfully.
Total customers: 96096
File saved: True

In [59]:
# Save product category analysis
category_summary.to_csv(
    OUTPUT_DIR / "product_category_analysis.csv",
    index=True
)

print("Product category analysis saved!")
print("Total categories:", len(category_summary))
print(
    "File saved:",
    (OUTPUT_DIR / "product_category_analysis.csv").exists()
)

Product category analysis saved!
Total categories: 74
File saved: True

In [60]:
rfm.to_csv(
    OUTPUT_DIR / "customer_rfm_segments.csv",
    index=True
)

print("RFM data saved!")
print("Total customers:", len(rfm))
print(
    "File saved:",
    (OUTPUT_DIR / "customer_rfm_segments.csv").exists()
)

RFM data saved!
Total customers: 93358
File saved: True

In [61]:
# Save cohort customer counts
cohort_data.to_csv(
    OUTPUT_DIR / "cohort_customer_counts.csv",
    index=False
)

# Save retention percentages
retention.to_csv(
    OUTPUT_DIR / "cohort_retention_percentages.csv"
)

print("Cohort analysis files saved!")

Cohort analysis files saved!

In [62]:
print("Files in output folder:")
for file in OUTPUT_DIR.iterdir():
    if file.is_file():
        print(file.name)

Files in output folder:
cohort_customer_counts.csv
cohort_retention_percentages.csv
customer_purchase_analysis.csv
customer_rfm_segments.csv
product_category_analysis.csv

In [63]:
# Load all 9 Olist datasets if not already loaded
file_names = {
    "orders": "olist_orders_dataset.csv",
    "customers": "olist_customers_dataset.csv",
    "items": "olist_order_items_dataset.csv",
    "payments": "olist_order_payments_dataset.csv",
    "reviews": "olist_order_reviews_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "category_translation": "product_category_name_translation.csv"
}

datasets = {}

for name, filename in file_names.items():
    path = DATA_DIR / filename

    if path.exists():
        datasets[name] = pd.read_csv(path)
    else:
        print("FILE MISSING:", filename)

print("Datasets loaded:", len(datasets))

Datasets loaded: 9

In [64]:
audit_results = []

for name, df in datasets.items():
    audit_results.append({
        "Dataset": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Duplicate_Rows": int(df.duplicated().sum()),
        "Missing_Cells": int(df.isna().sum().sum()),
        "Missing_Percentage": round(
            df.isna().sum().sum()
            / (df.shape[0] * df.shape[1]) * 100, 2
        ) if df.size else 0
    })

audit_df = pd.DataFrame(audit_results)

display(audit_df)

,Dataset,Rows,Columns,Duplicate_Rows,Missing_Cells,Missing_Percentage
0,orders,99441,8,0,4908,0.62
1,customers,99441,5,0,0,0.00
2,items,112650,7,0,0,0.00
3,payments,103886,5,0,0,0.00
4,reviews,99224,7,0,145903,21.01
5,products,32951,9,0,2448,0.83
6,sellers,3095,4,0,0,0.00
7,geolocation,1000163,5,261831,0,0.00
8,category_translation,71,2,0,0,0.00

In [65]:
expected_files = [
    "customer_purchase_analysis.csv",
    "product_category_analysis.csv",
    "customer_rfm_segments.csv",
    "cohort_customer_counts.csv",
    "cohort_retention_percentages.csv"
]

for filename in expected_files:
    file_path = OUTPUT_DIR / filename
    print(
        filename,
        "—",
        "Available" if file_path.exists() else "Not found"
    )

customer_purchase_analysis.csv — Available
product_category_analysis.csv — Available
customer_rfm_segments.csv — Available
cohort_customer_counts.csv — Available
cohort_retention_percentages.csv — Available

In [1]:
import os

print("Current folder:", os.getcwd())
print("Notebook files:", [
    f for f in os.listdir()
    if f.endswith(".ipynb")
])

Current folder: C:\Users\ishag\OneDrive\photos for ppt\Desktop\Ecommerce-Customer-Analytics
Notebook files: ['ecommerce_analysis.ipynb']